# Generated by Django 4.1.6 on 2023-02-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_contato_foto'),
        ('contatos', '0004_contato_foto'),
    ]

    operations = [
    ]
